---
version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
    groups:
      dotnet-servicing:
        patterns: ["System.*", "Microsoft.NET.Test.Sdk"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
