sonar.projectKey=windows-triage
sonar.projectName=Windows Triage
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/bin/**,**/obj/**,**/publish/**,**/artifacts/**,WindowsTriage_*/**,Diagnostic_*/**,Start-WindowsTriage.ps1,draft_script.ps1
sonar.test.exclusions=**/bin/**,**/obj/**,**/publish/**,**/artifacts/**
sonar.scm.disabled=true
sonar.sourceEncoding=UTF-8
